title: TiTTu ry
description: Tampereen TietoTeekkareiden tuki ry
sitename: Tampereen TietoTeekkareiden tuki ry
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
  - vanhat_hallitukset
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
